baseURL = "https://yurimalheiros.com/"
languageCode = "pt-br"
title = "Yuri Malheiros"
theme = "hugo-researcher"
publishDir = "docs"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[params]
  lang = "pt-br"
  author = "Yuri Malheiros"
  description = "Yuri Malheiros - professor da UFPB."
  favicon = "favicon-96x96.png"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  math = true
  [params.style]  # appearance options (can be omitted)
    pageWidth = "80ch"
    colorBlack = "#111111"
    colorRed = "#0000EE"
    colorWhite = "#ffffff"
